coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        threshold: 1.0%
    patch:
      default:
        threshold: 1.0%
    changes: false

  comment:
    layout: "diff"
    behavior: default

  ignore:
    - "AurorKitTests"
    - "Pods"
