coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: auto
        threshold: 1.0%
    patch:
      default:
        target: auto
        threshold: 1.0%
    changes: true

  comment:
    layout: header
    behavior: default

  ignore:
    - "AurorKitTests"
    - "Pods"
