coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: auto
        threshold: 1.0%

    patch:
      default:
        target: auto
        threshold: 1.0%

  comment:
    layout: header

  ignore:
    - "AurorKitTests"
    - "Pods"
