coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      patch:
        default:
          threshold: 0.1%
    patch:
      default:
        threshold: 1.0%

  comment:
    layout: reach, diff

  ignore:
    - "AurorKitTests"
    - "Pods"