included: 
  - AurorKit
  - AurorKitTests

disabled_rules:
  - closure_body_length
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - force_cast
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - implicitly_unwrapped_optional
  - missing_docs
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - notification_center_detachment
  - nslocalizedstring_key
  - object_literal
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - redundant_string_enum_value
  - sorted_imports
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - untyped_error_in_catch
  - unused_closure_parameter
  - unused_import
  - vertical_whitespace_opening_braces

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_acl
  - explicit_self
  - explicit_top_level_acl
  - fallthrough
  - file_header
  - file_length
  - first_where
  - for_where
  - force_try
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - nesting
  - no_fallthrough_only
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_focused_test
  - quick_discouraged_call
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_type_annotation
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - static_operator
  - strict_fileprivate
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_private_declaration
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - void_return
  - weak_computed_property
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

file_header:
  required_pattern: |
                    \/\/
                    \/\/  SWIFTLINT_CURRENT_FILENAME
                    \/\/  AurorKit
                    \/\/
                    \/\/  Created by \S+?\ \S+ on \d{2}\/\d{2}\/\d{4}\.
                    \/\/  Copyright © \d{4} Aurors\. All rights reserved\.
                    \/\/

file_length:
  warning: 500
  error: 600

function_body_length:
  warning: 40
  error: 50

function_parameter_count:
  warning: 4
  error: 5

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - to
    - i
    - j
    - x
    - y
    - z

large_tuple: 
  warning: 3
  error: 4

line_length:
  warning: 120
  error: 130
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

nesting:
  type_level: 
    warning: 1
    error: 2
  statement_level:
    warning: 4
    error: 5

type_body_length:
  warning: 500
  error: 600

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

warning_threshold: 4