language: objective-c
osx_image: xcode10.1

env:
  global:
    - WORKSPACE='AurorKit.xcworkspace'

    - IOS_SCHEME='AurorKit iOS'
    - MACOS_SCHEME='AurorKit macOS'
    - TVOS_SCHEME='AurorKit tvOS'

    - IOS_DESTINATION='platform=iOS Simulator,OS=12.1,name=iPhone XS'
    - MACOS_DESTINATION='platform=macOS'
    - TVOS_DESTINATION='platform=tvOS Simulator,OS=12.1,name=Apple TV 4K'

before_install:
  - pod repo update

install:
  - ./Bootstrap.sh

script:
  - set -o pipefail
  - swift --version

  - xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -destination "$IOS_DESTINATION" | xcpretty -c
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'AurorKit'

  - xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$TVOS_SCHEME" -destination "$TVOS_DESTINATION" | xcpretty -c
  - bash <(curl -s https://codecov.io/bash) -cF tvos -J 'AurorKit'

  - xcodebuild clean build test -workspace "$WORKSPACE" -scheme "$MACOS_SCHEME" -destination "$MACOS_DESTINATION" | xcpretty -c
  - bash <(curl -s https://codecov.io/bash) -cF osx -J 'AurorKit'

  - swiftlint --reporter junit

branches:
  only:
    - master
