language: objective-c
osx_image: xcode10.1
xcode_workspace: AurorKit.xcworkspace

matrix:
  include:
    - xcode_scheme: AurorKit iOS
      xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS
      xcode_sdk: iphonesimulator12.1

    - xcode_scheme: AurorKit macOS
      xcode_destination: platform=macOS
      xcode_sdk: macosx10.12

    - xcode_scheme: AurorKit tvOS
      xcode_destination: platform=tvOS Simulator,OS=12.1,name=Apple TV 4K
      xcode_sdk: tvos12.1

before_install:
  - pod repo update