language: objective-c
osx_image: xcode10.1

before_install:
  - pod repo update

install:
  - ./Bootstrap.sh

script:
  - set -o pipefail
  - swift --version
  - xcodebuild clean build test -workspace 'AurorKit.xcworkspace' -scheme 'AurorKit iOS' -sdk 'iphoneos12.1' -destination 'platform=iOS Simulator,OS=12.1,name=iPhone XS' | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'AurorKit'
  - xcodebuild clean build test -workspace 'AurorKit.xcworkspace' -scheme 'AurorKit tvOS' -sdk 'appletvos12.1' -destination 'platform=tvOS Simulator,OS=12.1,name=Apple TV 4K' | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-tvos.json" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF tvos -J 'AurorKit'
  - xcodebuild clean build test -workspace 'AurorKit.xcworkspace' -scheme 'AurorKit macOS' -sdk 'macosx10.14' -destination 'platform=macOS' | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF osx -J 'AurorKit'
  - swiftlint --reporter junit

branches:
  only:
    - master
