language: objective-c
osx_image: xcode10.1
xcode_workspace: AurorKit.xcworkspace
xcode_scheme: AurorKit iOS
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS
xcode_sdk: iphonesimulator12.1